### ISSUE TITLE
TagLib.framework/Headers/taglib.h:45:10: 'string' file not found

### ISSUE THREAD

**Issue by shmidt** [ap4y/Audio-Frameworks#2]
Thank you very much for sharing the code!

I've imported `TagLib.framework` and compiler shows error 
on line `#include <string>`:
`TagLib.framework/Headers/taglib.h:45:10: 'string' file not found`.
How can I shut him up? :)

**Comment by shmidt** [comment]
I've already found the answer:

```
#ifdef __cplusplus
#import <TagLib/tag.h>
#endif
```

**Comment by ap4y** [comment]
I think idiomatic solution here is to use `Objective-C++`. If you rename file to `.mm` compiler will use `c++` stdlib, which will give you `string.h`.
